rm(list=ls())

data1<- read.csv("C:/Users/User/OneDrive/Documents/Dissertation/AMZN_data_1999_2022.csv",header=T)
data2<-read.csv("C:/Users/User/OneDrive/Documents/Dissertation/MSFT(2000-2023).csv",header=T)
data3<-read.csv("C:/Users/User/OneDrive/Documents/Dissertation/NFLX.csv",header=T)

colnames(data1)

closing_price_amazon=log(data1$Close)
opening_price_amazon=log(data1$Open)
closing_price_microsoft=log(data2$Close)
opening_price_microsoft=log(data2$Open)
closing_price_netflix=log(data3$Close)
opening_price_netflix=log(data3$Open)

library(tseries)
library(forecast)

adf.test((closing_price_amazon))
adf.test(diff(closing_price_amazon))
adf.test((closing_price_microsoft))
adf.test(diff(closing_price_microsoft))
adf.test((closing_price_netflix))
adf.test(diff(closing_price_netflix))

adf.test((opening_price_amazon))
adf.test(diff(opening_price_amazon))
adf.test((opening_price_microsoft))
adf.test(diff(opening_price_microsoft))
adf.test((opening_price_netflix))
adf.test(diff(opening_price_netflix))

plot(((closing_price_amazon)),type="l")
plot(((closing_price_microsoft)),type="l")
plot(((closing_price_netflix[1:100])),type="l")

plot(((opening_price_amazon)),type="l")
plot(((opening_price_microsoft)),type="l")
plot(((opening_price_netflix)),type="l")

acf(diff(closing_price_amazon))
pacf((closing_price_amazon))
acf(diff(closing_price_microsoft))
pacf((closing_price_microsoft))
acf(diff(closing_price_netflix))
pacf(closing_price_netflix)

acf(diff(opening_price_amazon))
pacf((opening_price_amazon))
acf(diff(opening_price_microsoft))
pacf((opening_price_microsoft))
acf(diff(opening_price_netflix))
pacf(opening_price_netflix)

auto.arima(closing_price_amazon)
fit1=arima((closing_price_amazon),order=c(1,1,2))
lines(fitted(fit1),col="red")
auto.arima(closing_price_microsoft)
fit2=arima(closing_price_microsoft,order=c(1,1,1))
lines(fitted(fit2),col="red")
auto.arima(closing_price_netflix)
fit3=arima(closing_price_netflix,order=c(1,1,0))
lines(fitted(fit3),col="red")

auto.arima(opening_price_amazon)
fit1_o=arima((opening_price_amazon),order=c(1,1,1))
lines(fitted(fit1_o),col="red")
auto.arima(opening_price_microsoft)
fit2_o=arima(closing_price_microsoft,order=c(1,1,4))
lines(fitted(fit2_o),col="red")
auto.arima(opening_price_netflix)
fit3_o=arima(opening_price_netflix,order=c(1,1,2))
lines(fitted(fit3_o),col="red")


